### ISSUE TITLE
Can't access to REST Interface swagger-ui

### ISSUE THREAD

**Issue by NortonHua** [Keyfactor/ejbca-ce#118] opened 2022-09-24 14:48 UTC
I run a container use ejbca-ce:7.9.0.2 , setting ejbca.productionmode=false and enable for the REST on adminweb page，but I can't access to swagger-ui through URL https://localhost:8443/ejbca/swagger-ui；Is there anyone who can help me?

**Comment by primetomas** [comment] 2022-09-28 07:06
Hi, enabling the swagger UI requires rebuild of the software, it is not even included in the ejbca.ear file present by default in the container. You have to build from source to enable development mode.

Cheers,
Tomas

**Comment by primetomas** [comment] 2022-09-28 07:08
It's by design, and no roadmap plan to change it. You can get help from example ansible playbooks to deploy ejbca from source.
You can also re-build ejbca.ear from source and replace the version inside the container.

Closing the issue.

Regards,
Tomas

**Closed by primetomas** 2022-09-28 07:08 UTC
