### ISSUE TITLE
Java 17 and error with PKCS#11

### ISSUE THREAD

**Issue by Stueypoo** [Keyfactor/ejbca-ce#438] opened 2023-12-09 01:39 UTC
For testing, I have a SoftHSM (v2) installed. If I try to access with the ClientToolBox, there is an error thrown with Java 17. If I run again, with the only change to use Java 11, then it works. This is the main exception which I've seen other people experience, but I havn't seen a resolution anywhere.

```
sunpkcs11: Multi-threaded initialization failed: sun.security.pkcs11.wrapper.PKCS11Exception: CKR_CRYPTOKI_NOT_INITIALIZED
2023-12-09 12:12:42,170 ERROR [com.keyfactor.util.keys.token.pkcs11.SunP11SlotListWrapper] Wrong arguments were passed to sun.security.pkcs11.wrapper.PKCS11.CK_C_INITIALIZE_ARGS.getInstance threw an exception for log.error(msg, e)

```
Full debug output here for Java 17:

```
$ export JAVA_HOME=/usr/lib/jvm/jre-17
$ ./ejbcaClientToolBox.sh PKCS11HSMKeyTool test /usr/lib64/softhsm/libsofthsm.so i0
Test of keystore with ID i0.
SunPKCS11 loading --name = libsofthsm.so-slot-1
library = /usr/lib64/pkcs11/libsofthsm2.so
slot = -1
attributes(*, CKO_PUBLIC_KEY, *) = {
  CKA_TOKEN = false
  CKA_ENCRYPT = true
  CKA_VERIFY = true
  CKA_WRAP = true
}
attributes(*, CKO_PRIVATE_KEY, *) = {
  CKA_DERIVE = false
  CKA_TOKEN = true
  CKA_PRIVATE = true
  CKA_SENSITIVE = true
  CKA_EXTRACTABLE = false
  CKA_DECRYPT = true
  CKA_SIGN = true
  CKA_UNWRAP = true
}
disabledMechanisms = {
  CKM_SHA1_RSA_PKCS
  CKM_SHA256_RSA_PKCS
  CKM_SHA384_RSA_PKCS
  CKM_SHA512_RSA_PKCS
  CKM_MD2_RSA_PKCS
  CKM_MD5_RSA_PKCS
  CKM_DSA_SHA1
  CKM_ECDSA_SHA1
}
attributes(*, CKO_SECRET_KEY, *) = {
  CKA_SENSITIVE = true
  CKA_EXTRACTABLE = false
  CKA_ENCRYPT = true
  CKA_DECRYPT = true
  CKA_SIGN = true
  CKA_VERIFY = true
  CKA_WRAP = true
  CKA_UNWRAP = true
}

sunpkcs11: Initializing PKCS#11 library /usr/lib64/pkcs11/libsofthsm2.so
sunpkcs11: Multi-threaded initialization failed: sun.security.pkcs11.wrapper.PKCS11Exception: CKR_CRYPTOKI_NOT_INITIALIZED
2023-12-09 12:12:42,170 ERROR [com.keyfactor.util.keys.token.pkcs11.SunP11SlotListWrapper] Wrong arguments were passed to sun.security.pkcs11.wrapper.PKCS11.CK_C_INITIALIZE_ARGS.getInstance threw an exception for log.error(msg, e)
java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at com.keyfactor.util.keys.token.pkcs11.SunP11SlotListWrapper.<init>(SunP11SlotListWrapper.java:144) [x509-common-util-0.6.0-SNAPSHOT.jar:?]
	at com.keyfactor.util.keys.token.pkcs11.SunP11SlotListWrapperFactory.getInstance(SunP11SlotListWrapperFactory.java:74) [x509-common-util-0.6.0-SNAPSHOT.jar:?]
	at com.keyfactor.util.keys.token.pkcs11.SunP11SlotListWrapperFactory.getInstance(SunP11SlotListWrapperFactory.java:35) [x509-common-util-0.6.0-SNAPSHOT.jar:?]
	at com.keyfactor.util.keys.token.pkcs11.Pkcs11SlotLabel.getSlotListWrapper(Pkcs11SlotLabel.java:566) [x509-common-util-0.6.0-SNAPSHOT.jar:?]
	at com.keyfactor.util.keys.token.pkcs11.Pkcs11SlotLabel.getProvider(Pkcs11SlotLabel.java:120) [x509-common-util-0.6.0-SNAPSHOT.jar:?]
	at com.keyfactor.util.keys.token.pkcs11.Pkcs11SlotLabel.getP11Provider(Pkcs11SlotLabel.java:551) [x509-common-util-0.6.0-SNAPSHOT.jar:?]
	at org.ejbca.util.keystore.KeyStoreToolsFactory.getInstance(KeyStoreToolsFactory.java:40) [clientToolBox.jar:EJBCA 8.0 Enterprise (working copy)]
	at org.ejbca.util.keystore.KeyStoreToolsFactory.getInstance(KeyStoreToolsFactory.java:95) [clientToolBox.jar:EJBCA 8.0 Enterprise (working copy)]
	at org.ejbca.util.keystore.KeyStoreToolsFactory.getInstance(KeyStoreToolsFactory.java:112) [clientToolBox.jar:EJBCA 8.0 Enterprise (working copy)]
	at org.ejbca.ui.cli.KeyStoreContainerTest.getKeyStoreTools(KeyStoreContainerTest.java:186) [clientToolBox.jar:EJBCA 8.0 Enterprise (working copy)]
	at org.ejbca.ui.cli.KeyStoreContainerTest.startNormal(KeyStoreContainerTest.java:136) [clientToolBox.jar:EJBCA 8.0 Enterprise (working copy)]
	at org.ejbca.ui.cli.KeyStoreContainerTest.test(KeyStoreContainerTest.java:84) [clientToolBox.jar:EJBCA 8.0 Enterprise (working copy)]
	at org.ejbca.ui.cli.HSMKeyTool.doIt(HSMKeyTool.java:677) [clientToolBox.jar:EJBCA 8.0 Enterprise (working copy)]
	at org.ejbca.ui.cli.HSMKeyTool.execute(HSMKeyTool.java:737) [clientToolBox.jar:EJBCA 8.0 Enterprise (working copy)]
	at org.ejbca.ui.cli.ClientToolBox.executeIfSelected(ClientToolBox.java:40) [clientToolBox.jar:EJBCA 8.0 Enterprise (working copy)]
	at org.ejbca.ui.cli.ClientToolBox.main(ClientToolBox.java:72) [clientToolBox.jar:EJBCA 8.0 Enterprise (working copy)]
Caused by: sun.security.pkcs11.wrapper.PKCS11Exception: CKR_CRYPTOKI_NOT_INITIALIZED
	at sun.security.pkcs11.wrapper.PKCS11.C_GetInfo(Native Method) ~[jdk.crypto.cryptoki:?]
	at sun.security.pkcs11.wrapper.PKCS11$SynchronizedPKCS11.C_GetInfo(PKCS11.java:1681) ~[jdk.crypto.cryptoki:?]
	at sun.security.pkcs11.wrapper.PKCS11.<init>(PKCS11.java:156) ~[jdk.crypto.cryptoki:?]
	at sun.security.pkcs11.wrapper.PKCS11$SynchronizedPKCS11.<init>(PKCS11.java:1668) ~[jdk.crypto.cryptoki:?]
	at sun.security.pkcs11.wrapper.PKCS11.getInstance(PKCS11.java:194) ~[jdk.crypto.cryptoki:?]
	at sun.security.pkcs11.wrapper.PKCS11.getInstance(PKCS11.java:166) ~[jdk.crypto.cryptoki:?]
	... 20 more
2023-12-09 12:12:42,182 ERROR [org.ejbca.ui.cli.KeyStoreContainerTest] Not possible to load keys.

```

Here is the output for Java 11:

```
$ export JAVA_HOME=/usr/lib/jvm/jre-11
$ ./ejbcaClientToolBox.sh PKCS11HSMKeyTool test /usr/lib64/softhsm/libsofthsm.so i0
Test of keystore with ID i0.
SunPKCS11 loading --name = libsofthsm.so-slot-1
library = /usr/lib64/pkcs11/libsofthsm2.so
slot = -1
attributes(*, CKO_PUBLIC_KEY, *) = {
  CKA_TOKEN = false
  CKA_ENCRYPT = true
  CKA_VERIFY = true
  CKA_WRAP = true
}
attributes(*, CKO_PRIVATE_KEY, *) = {
  CKA_DERIVE = false
  CKA_TOKEN = true
  CKA_PRIVATE = true
  CKA_SENSITIVE = true
  CKA_EXTRACTABLE = false
  CKA_DECRYPT = true
  CKA_SIGN = true
  CKA_UNWRAP = true
}
disabledMechanisms = {
  CKM_SHA1_RSA_PKCS
  CKM_SHA256_RSA_PKCS
  CKM_SHA384_RSA_PKCS
  CKM_SHA512_RSA_PKCS
  CKM_MD2_RSA_PKCS
  CKM_MD5_RSA_PKCS
  CKM_DSA_SHA1
  CKM_ECDSA_SHA1
}
attributes(*, CKO_SECRET_KEY, *) = {
  CKA_SENSITIVE = true
  CKA_EXTRACTABLE = false
  CKA_ENCRYPT = true
  CKA_DECRYPT = true
  CKA_SIGN = true
  CKA_VERIFY = true
  CKA_WRAP = true
  CKA_UNWRAP = true
}

sunpkcs11: Initializing PKCS#11 library /usr/lib64/pkcs11/libsofthsm2.so
Information for provider SunPKCS11-libsofthsm.so-slot-1
Library info:
  cryptokiVersion: 2.40
  manufacturerID: SoftHSM                         
  flags: 0
  libraryDescription: Implementation of PKCS11        
  libraryVersion: 2.06
All slots: 88042976, 1
Slots with tokens: 88042976, 1
Slot info for slot 88042976:
  slotDescription: SoftHSM slot ID 0x53f6de0                                       
  manufacturerID: SoftHSM project                 
  flags: CKF_TOKEN_PRESENT
  hardwareVersion: 2.06
  firmwareVersion: 2.06
Token info for token in slot 88042976:
  label: SoftHSM1234                     
  manufacturerID: SoftHSM project                 
  model: SoftHSM v2      
  serialNumber: 0c43a286053f6de0
  flags: CKF_RNG | CKF_LOGIN_REQUIRED | CKF_USER_PIN_INITIALIZED | CKF_RESTORE_KEY_NOT_NEEDED | CKF_TOKEN_INITIALIZED
  ulMaxSessionCount: CK_EFFECTIVELY_INFINITE
  ulSessionCount: CK_UNAVAILABLE_INFORMATION
  ulMaxRwSessionCount: CK_EFFECTIVELY_INFINITE
  ulRwSessionCount: CK_UNAVAILABLE_INFORMATION
  ulMaxPinLen: 255
  ulMinPinLen: 4
  ulTotalPublicMemory: CK_UNAVAILABLE_INFORMATION
  ulFreePublicMemory: CK_UNAVAILABLE_INFORMATION
  ulTotalPrivateMemory: CK_UNAVAILABLE_INFORMATION
  ulFreePrivateMemory: CK_UNAVAILABLE_INFORMATION
  hardwareVersion: 2.06
  firmwareVersion: 2.06
  utcTime: 2023120901063400
Mechanism CKM_AES_CBC:
  ulMinKeySize: 16
  ulMaxKeySize: 32
  flags: 131840 = CKF_ENCRYPT | CKF_DECRYPT | CKF_WRAP
  (etc)

```

And for completeness, I did add 'debug' and the 'add-exports' command to the shell script:

`${javaCmd} ${JAVA_OPT} -Djava.security.debug=sunpkcs11 --add-exports=jdk.crypto.cryptoki/sun.security.pkcs11.wrapper=ALL-UNNAMED -Dlog4j1.compatibility=true -cp "$TOOLBOX_HOME/clientToolBox.jar:${TOOLBOX_HOME}/ext/*" org.ejbca.ui.cli.ClientToolBox "${@}"
`

**Comment by primetomas** [comment] 2023-12-11 09:57
What version of EJBCA is this?

**Comment by primetomas** [comment] 2023-12-12 16:29
Closing this issue. I just tested clientToolBox with Java 17. After adding the "--add-exports=jdk.crypto.cryptoki/sun.security.pkcs11.wrapper=ALL-UNNAMED" in clientToolBox.sh it works fine.

java -version
openjdk version "17.0.9" 2023-10-17
OpenJDK Runtime Environment (build 17.0.9+9-Ubuntu-122.04)
OpenJDK 64-Bit Server VM (build 17.0.9+9-Ubuntu-122.04, mixed mode, sharing)

```
./ejbcaClientToolBox.sh PKCS11HSMKeyTool test /usr/lib/softhsm/libsofthsm2.so 2062286291
Test of keystore with ID 2062286291.
PKCS11 Token [SunPKCS11-libsofthsm2.so-slot2062286291] Password: 
Not testing keys with alias testKey. KeyStoreException getting key: java.security.KeyStoreException: invalid KeyStore state: found 2 private keys sharing CKA_ID testKey

Testing of key: encryptionKey ÅaÄbbÖcccäâãêëẽć©A
Private part:
SunPKCS11-libsofthsm2.so-slot2062286291 RSA private key, 1024 bitstoken object, sensitive, unextractable)
RSA key:
  modulus: a61171d6241440c6af795034a0a5c72c9f6cd24070ce6403379abffcd1e6b54ad244179e9b579fec71a9b87f72f3a4df5be64ff21b8719d0471f4e9ebd4b9dc3967553bd699615340af09c78c755e8b7c529f2da4adb80b11d1aac1f44d2bd4da7d50f8408ecd19a95271636f87fd5373589dc84603feb3fb00d44cc61b66293
  public exponent: 10001
encryption provider: SunJCE version 17; decryption provider: SunPKCS11-libsofthsm2.so-slot2062286291 version 17; modulus length: 1024; byte length 117. The decoded byte string is equal to the original!
2023-12-12 17:28:28,070 INFO  [com.keyfactor.util.keys.SignWithWorkingAlgorithm] Signature algorithm 'SHA1WithRSA' working for provider 'SunPKCS11-libsofthsm2.so-slot2062286291 version 17'.
Signature test of key encryptionKey ÅaÄbbÖcccäâãêëẽć©A: signature length 128; first byte 5d; verifying true
Signings per second: 4257
Decryptions per second: 4408

Testing of key: defaultKey ÅaÄÖbåäöc«»©“”nµA
Private part:
SunPKCS11-libsofthsm2.so-slot2062286291 RSA private key, 1024 bitstoken object, sensitive, unextractable)
RSA key:
  modulus: de6aa71a67b0c5f4d805a9a3ffd41a1cb336eaa8b0ec8d4dd507f2181ba0a790b3211bcece3d089787b7253d7b45cc5b33070fb02cac757798a6827a193aa065fa65cf5a2c93754e5d0b010c5b9e3af3efeb2d2f26265dbf83787784a857e3dee50c2d9f8b6ad895dde750dc07110b64b6cd6b0e797cb43ad4503259f0df701b
  public exponent: 10001
encryption provider: SunJCE version 17; decryption provider: SunPKCS11-libsofthsm2.so-slot2062286291 version 17; modulus length: 1024; byte length 117. The decoded byte string is equal to the original!
Signature test of key defaultKey ÅaÄÖbåäöc«»©“”nµA: signature length 128; first byte 54; verifying true
Signings per second: 5182
Decryptions per second: 4906

```

**Comment by Stueypoo** [comment] 2023-12-12 21:54
Thanks for responses. The slot was initialised and in my case the test worked fin with Java v11.  I understood that using "i0" would refer to the slot index rather than the slot number. I have actually tried using slot labels and slot numbers and I would get the same error everytime with Java 17. 

The EJBCA version is 8.0 CE.

The Java 17 version is:
openjdk version "17.0.6" 2023-01-17 LTS
OpenJDK Runtime Environment (Red_Hat-17.0.6.0.10-3.el9_1) (build 17.0.6+10-LTS)
OpenJDK 64-Bit Server VM (Red_Hat-17.0.6.0.10-3.el9_1) (build 17.0.6+10-LTS, mixed mode, sharing)

OS is RHEL:
$ cat /etc/redhat-release 
  Red Hat Enterprise Linux release 9.2 (Plow)

SoftHSM version:
$ softhsm2-util --version 
2.6.1

**Comment by primetomas** [comment] 2023-12-13 08:35
Ok, let me look again, CKR_CRYPTOKI_NOT_INITIALIZED may be another thing actually.

**Comment by primetomas** [comment] 2023-12-13 09:19
I retested now with the code from github.

```
>git clone git@github.com:Keyfactor/ejbca-ce.git ejbca-ce-github
>cd ejbca-ce-github
>ant clientToolBox
>cd dist/clientToolBox
>java -version
openjdk version "17.0.9" 2023-10-17
OpenJDK Runtime Environment (build 17.0.9+9-Ubuntu-122.04)
OpenJDK 64-Bit Server VM (build 17.0.9+9-Ubuntu-122.04, mixed mode, sharing)

>./ejbcaClientToolBox.sh PKCS11HSMKeyTool test /usr/lib/softhsm/libsofthsm2.so 2062286291

Test of keystore with ID 2062286291.
PKCS11 Token [SunPKCS11-libsofthsm2.so-slot2062286291] Password: 
Not testing keys with alias testKey. KeyStoreException getting key: java.security.KeyStoreException: invalid KeyStore state: found 2 private keys sharing CKA_ID testKey

Testing of key: encryptionKey ÅaÄbbÖcccäâãêëẽć©A
Private part:
SunPKCS11-libsofthsm2.so-slot2062286291 RSA private key, 1024 bitstoken object, sensitive, unextractable)
RSA key:
  modulus: a61171d6241440c6af795034a0a5c72c9f6cd24070ce6403379abffcd1e6b54ad244179e9b579fec71a9b87f72f3a4df5be64ff21b8719d0471f4e9ebd4b9dc3967553bd699615340af09c78c755e8b7c529f2da4adb80b11d1aac1f44d2bd4da7d50f8408ecd19a95271636f87fd5373589dc84603feb3fb00d44cc61b66293
  public exponent: 10001
encryption provider: SunJCE version 17; decryption provider: SunPKCS11-libsofthsm2.so-slot2062286291 version 17; modulus length: 1024; byte length 117. The decoded byte string is equal to the original!
2023-12-13 10:17:34,287 INFO  [com.keyfactor.util.keys.SignWithWorkingAlgorithm] Signature algorithm 'SHA1WithRSA' working for provider 'SunPKCS11-libsofthsm2.so-slot2062286291 version 17'.
Signature test of key encryptionKey ÅaÄbbÖcccäâãêëẽć©A: signature length 128; first byte 5d; verifying true
Signings per second: 3213
Decryptions per second: 3547

>softhsm2-util --version
2.6.1
```

So I still can not reproduce this. This is on Ubuntu 22.04, so it would be if it was very specific to RHEL 9?

**Comment by Stueypoo** [comment] 2023-12-13 21:39
Thanks for looking into this. I can continue with Java 11, so it isn't a big problem. Very odd though.

**Comment by primetomas** [comment] 2023-12-13 21:58
Thanks for the report. We'll see how it evolves when Java 17 becomes more frequently used. Closing for now.

**Comment by Stueypoo** [comment] 2023-12-14 05:18
Something interesting to add. On the same server I download OpenJDK 17 +35, and ran the ClientToolBox using this Java runtime and access to the SoftHSM works fine.  This Java version is:
$JAVA_HOME/bin/java -version
openjdk version "17" 2021-09-14
OpenJDK Runtime Environment (build 17+35-2724)
OpenJDK 64-Bit Server VM (build 17+35-2724, mixed mode, sharing)

So it seems there is something odd with the RHEL version of OpenJDK v17.

**Comment by primetomas** [comment] 2023-12-14 07:03
Great news, thanks.

**Comment by xipki** [comment] 2023-12-21 21:08
This may be RHEL specific issue. See my implementation.

**Comment by primetomas** [comment] 2023-12-22 08:43
Thanks, that is helpful. Will look at that for the next release.

**Comment by primetomas** [comment] 2024-01-14 07:16
Jira ticket (not publicly visible now, but will be in the future): https://jira.primekey.se/browse/ECA-12074

**Comment by primetomas** [comment] 2024-01-16 14:33
We do have the check for the additional argument to PKCS11 already. This seems to be related to CK_C_INITIALIZE_ARGS, and I added code to construct that with getDeclaredConstructor().newInstance(). Hopefully it helps in the next release.

**Closed by primetomas** 2024-01-16 14:33 UTC
