### ISSUE TITLE
Can not select PEM as certificate container when issuing user certificate since 7.11.0 (only if Key Recovery is enabled)

### ISSUE THREAD

**Issue by Pinkbyte** [Keyfactor/ejbca-ce#220] opened 2023-01-18 09:21 UTC
After updating to 7.11.0 button 'Download PEM' is missing from RA web when issuing user certificates.

End entity profile of that user has 'Default token' set as PEM and also have PEM in list of available container types.

Download buttons for other types(JKS and PKCS#12 in this case) are present.

EJBCA installed from Docker container (keyfactor/ejbca-ce:7.11.0)

**Comment by primetomas** [comment] 2023-01-18 15:17
Did you set PEM as the token type when you added the end entity? I started the latest container, added an end entity "test" with PEM token type (server generated keys), then I went into the RA Web and selected "Use username". 
See screenshot.
![pem-github](https://user-images.githubusercontent.com/28708578/213210038-c1191db0-8d40-44d5-8832-ec2228cb7a12.png)

**Comment by Pinkbyte** [comment] 2023-01-18 16:43
Yes, PEM token type was default from the beginning(when we first deployed EJBCA, it was 6.4.0 IIRC) and that does not changed. I tried:

1) unset PEM token(both default and in supported token list), save end entity profile, and set it back again - no difference;
2) change end entity profile for user back and forth;
3) try different user(with different profile, that also have PEM as supported token type) - no luck either.

I want to clarify - the problem does NOT happen if old publicweb interface used(that one with big red notice about it is deprecated). The problem is only with RA web.

No errors observed in container logs either during enrollment...

![end_entity_token_types](https://user-images.githubusercontent.com/1030422/213241425-75bc39ec-f1ca-48e0-a412-04ec4c4bb09c.png)

**Comment by primetomas** [comment] 2023-01-19 13:49
In RA Web, are you using "Enroll->Make new request"?

**Comment by Pinkbyte** [comment] 2023-01-19 18:23
No, i am using "Enroll->Use Username". But in "Enroll->Make new request", at bottom of the page, i am also seeing only JKS and PKCS#12 - no PEM

**Comment by Pinkbyte** [comment] 2023-01-20 13:46
Attaching portion of end entity(not profile one, just one end entity) settings:
![end_entity](https://user-images.githubusercontent.com/1030422/213711472-4d48a67b-4027-4255-8e5f-145cc84f3b4e.png)

So, token type should be PEM, but it still not available :-(

**Comment by primetomas** [comment] 2023-01-31 10:05
Very strange. I am trying to reproduce this but failing.

I installed a new setup:
docker pull keyfactor/ejbca-ce
docker run -it --rm -p 80:8080 -p 443:8443 -h mycahostname -e TLS_SETUP_ENABLED="simple" keyfactor/ejbca-ce

Created a new certificate profile test, allowing RSA, ECDSA and Ed25519, default and allowed CA "Management CA"
Created a new end entity profile, like your above, profile Test, CA Management CA, tokens like your above.
Added a new end entity, like yours above
Enroll with RA Web->Use Username->Username/code. All three buttons are visible JKS, P12 and PEM.

If you do this with a fresh container, do you still get your result?

**Comment by Pinkbyte** [comment] 2023-01-31 10:34
Unfortunately i can not access only public web in fresh deployed container. When trying to access https:// i get non-trusted certificate warning(which is absolutely fine) and then, after agreeing with it - PR_END_OF_FILE_ERROR(i am using Firefox, but Chrome throws similar error). Error looks like i am trying to access Admin web interface without admin certificate installed in browser.

Should not i generate admin certificate first with EJBCA CLI tools(i barely remember how it was deployed 6 or 7 years ago), or TLS_SETUP_ENABLED="simple" does not require this?

**Comment by primetomas** [comment] 2023-01-31 10:58
TLS_SETUP_ENABLED="simple" does not require any authentication. If you get a question for client cert (because you happen to have on installed) just click cancel.

**Comment by Pinkbyte** [comment] 2023-01-31 11:30
Yeah, workaround it by using clean browser profile.

Regarding the main issue, i think i find the source of the problem. If End entity profile contains 'key recovery' enabled (in my case - also with 'required' and 'reuse old certificate') - PEM is not available in RA web, not matter what token options are in 'End entity profile'.

Without key recovery - it works just fine.

**Comment by Pinkbyte** [comment] 2023-06-30 06:34
Issue is still present in 8.0.0

**Comment by primetomas** [comment] 2023-06-30 09:32
Created an internal issue, for follow ups after public web removal.

**Comment by primetomas** [comment] 2023-11-01 14:32
This is being fixed in EJBCA 8.2. Closing this issue.

**Closed by primetomas** 2023-11-01 14:32 UTC

**Comment by Pinkbyte** [comment] 2024-01-10 11:17
Unfortunately this is still NOT fixed in 8.2.0.1 (installed from keyfactor/ejbca-ce:8.2.0.1 docker image)

End Entity with Key Recovery enabled has no download PEM button in RA GUI(even if 'Token' field in End Entity is set to PEM), only JKS and PKCS#12

**Comment by primetomas** [comment] 2024-01-25 07:29
Ok apparently fixed so that for initial enrollment you can use PEM, but not when you want to recover keys.
Tracked as https://jira.primekey.se/browse/ECA-12154

**Comment by Pinkbyte** [comment] 2024-11-27 08:23
Unfortunately it is still not fixed in 8.3.2 :-(
