### ISSUE TITLE
Certificate revoked with hold and unrevoke with removeFromURL (behavior different depends on the presence of invalidityDate)

### ISSUE THREAD

**Issue by syisunny** [Keyfactor/ejbca-ce#505] opened 2024-02-13 17:13 UTC
for revokeCert in EndEntityManagementSessionBean, the removeFromCRL is not working if invalidityDate is present.

if invalidityDate is null, the removeFromCRL call is working.

it looks like an issue in CertificateStoreSessionBean.

### Discussed in https://github.com/Keyfactor/ejbca-ce/discussions/498

<div type='discussions-op-text'>

<sup>Originally posted by **syisunny** February  8, 2024</sup>
Hello,
on ejbca 8.2.0.1, I find that there is a change for the revoke api in revokeCert in EndEntityManagementSessionBean.
I create a certificate and call this api revokeCert with reason REVOCATION_REASON_CERTIFICATEHOLD. The call successed.
`
15:30:13,271 INFO  [org.cesecore.audit.impl.log4j.Log4jDevice] (default task-21) 2024-02-08 15:30:13+00:00;CERT_REVOKED;SUCCESS;CERTIFICATE;CORE;ejbca;1788025220;653E063325F82ED7124FDDE14FD4765A1683D355;Yqb8SrZ8AKsb1B_Generic MO Client 1m;msg=Invalidity date for revoked certificate has been changed, for username 'Yqb8SrZ8AKsb1B_Generic MO Client 1m', fp=1483e26b8c7bfb69a4b3082ab117224656cd9eeb, revocationReason=6, subjectDN 'CN=Yqb8SrZ8AKsb1B,OU=TEST1-OU,O=TEST1-O,DC=TEST-DC', issuerDN 'CN=Generic Operation SubCA1,OU=QA4,O=TKM,C=FR', serialNo=653E063325F82ED7124FDDE14FD4765A1683D355.
`

then i call this revokeCert API again with reason REVOCATION_REASON_REMOVEFROMCRL, the call successed. from the log, i could see 
`15:30:13,377` INFO  [org.ejbca.core.ejb.ca.revoke.RevocationSessionBean] (default task-21) Republished unrevoked cert, reason: 8.`

but from the EJBCA Admin GUI, it is still on hold

![image](https://github.com/Keyfactor/ejbca-ce/assets/5735654/af3be4dd-b2a5-4a43-9007-a0a4db502602)

before with ejbca 7.11, the certificate became unrevoked after the call of removeFromCRL.

what do you think? from the release note, i didn't find the change about this revoke behavior.

Best regards,
Yi
</div>

**Comment by primetomas** [comment] 2024-02-15 09:29
Internal note: caused by ECA-10974 and specifically ECA-11255

**Comment by primetomas** [comment] 2024-03-18 09:40
Additional note. InvalidityDate is not logical to use for unrevocation. invalidityDate according to RFC5280 is to set a date when a key compromise or similar happened. It has no function for non revoked certificates. So just use null for unrevocation.

**Comment by primetomas** [comment] 2024-04-30 14:30
This has been fixed and will be released in the upcoming may release. Thanks for the report.

**Closed by primetomas** 2024-04-30 14:30 UTC
