### ISSUE TITLE
Editing CT Logs caused major ejbca outage

### ISSUE THREAD

**Issue by MichaelRisthausAtos** [Keyfactor/ejbca-ce#195] opened 2022-12-20 09:30 UTC
In addition to our mail to support@keyfactor.com:

today we edited the CT Logs in our ejbca production installation. We added 7 new entries for 2024. Since the ones from letsencrypt are now split into two (2024h1 and 2024h2), we used the log sharding feature:

![image](https://user-images.githubusercontent.com/12182550/208632658-7a7ab83e-8553-4416-bfa4-37e8326a1c61.png)

This caused a major ejbca outage. The log was full with stacktraces, all for the same error (see attachment):

`Prevented unauthorized deserialization attempt for type 'java.util.Date': java.util.Date: static final long serialVersionUID = 7523967970034938905L;
`

Even a restart of the wildfly server and a clean redeployment didn’t cure ejbca.

The only chance we had was to import the data of the table GlobalConfigurationData from a fresh database backup.

**Comment by MichaelRisthausAtos** [comment] 2022-12-20 09:30
[ejbca_stacktrace.txt](https://github.com/Keyfactor/ejbca-ce/files/10267139/ejbca_stacktrace.txt)

**Comment by primetomas** [comment] 2022-12-20 09:52
Thanks for the report. 
As it was reported to support already, it will be registered as an issue with EJBCA. I will close this issue here. 
I could not reproduce it in the latest version of EJBCA, but support have access to your version and can look at that specifically.

**Closed by primetomas** 2022-12-20 09:52 UTC
