### ISSUE TITLE
[BUG] the admin web page for CMP aliases misses the 'Add' button

### ISSUE THREAD

**Issue by kuehne-trustable-de** [Keyfactor/ejbca-ce#473] opened 2024-01-16 12:17 UTC
**Describe the Bug**

After a fresh setup the admin web page for CMP administration misses the 'Add' button to create a new CMP alias.

**To Reproduce**

1. Go to '/ejbca/adminweb'
2. Click on 'CMP Configuration'
3. No 'Add' button available

**Expected Behavior**

The previous versions present a text entry field for the name and an 'Add' button to create a new CMP alias.

**Screenshots and Logs**

If applicable, add screenshots and logs to help explain your problem.

**Product Deployment** 

Please complete the following information:
 - Deployment format: docker image
REPOSITORY           TAG       IMAGE ID       CREATED        SIZE
mariadb              latest    c74611c2858a   4 weeks ago    404MB
keyfactor/ejbca-ce   latest    f2a4f1567c7f   5 weeks ago    568MB

 - Version:  EJBCA 8.2.0.1 Community (39b6c93b944edfc654aa90ecfeba3c7986ff224d) 

**Desktop**
Docker host:
 - OS: Ubuntu 22.04
 - Browser: Firefox
 - Version: 121.0

![ejbca admin CMP](https://github.com/Keyfactor/ejbca-ce/assets/3855221/acfd5ec9-0deb-4298-9002-73023f984b02)

**Comment by svenska-primekey** [comment] 2024-01-16 13:55
Thanks for reporting, I'll report this regression over to the devs.

**Comment by primetomas** [comment] 2024-02-21 14:51
There is a similar error, but when deleting SCEP aliases. This was due to some modernization-refactoring of these web pages.

If you want to make a quick fix, there is a line in cmpaliases.xhtml:

<h:form id="cmpaliasesform" rendered="#{web.ejbcaWebBean.runningEnterprise}">

the "rendered="#{web.ejbcaWebBean.runningEnterprise}" should obviously not be there :-(.

Will close this ticket as it's fixed for the next release. Thank you very much for the report.

**Closed by primetomas** 2024-02-21 14:51 UTC
Labels: bug

**Comment by murphy1312** [comment] 2024-05-15 07:26
Is there any workaround if running inside a non-root docker container?
A database insert would work I guess, but I have not figured out which table(s) it goes.

**Comment by primetomas** [comment] 2024-05-15 13:47
It would be GlobalConfigurationData, not the easiest table to work with unfortunately, but if you have a previous installation with a row for CMP you can copy that.

The new release will be out here in just a couple of weeks now.

**Comment by murphy1312** [comment] 2024-05-15 14:55
> It would be GlobalConfigurationData, not the easiest table to work with unfortunately, but if you have a previous installation with a row for CMP you can copy that.
> 
> The new release will be out here in just a couple of weeks now.

Thanks. Then I'll be using the 8.0.0 Release for now

**Comment by thomascenni** [comment] 2024-05-24 11:40
Hello, I am on:
Version : EJBCA 8.2.0.1 Community (39b6c93b944edfc654aa90ecfeba3c7986ff224d)
and the bug is still present.
Is there a workaround? Making a POST request for example ?

**Comment by primetomas** [comment] 2024-05-27 14:20
The new release will come June 13. Waiting for that I think is the easiest workaround. Otherwise starting with EJBCA 8.0, and upgrading to EJBCA 8.2.
